### PR TITLE
Fixes #1160 Add transitionend event to enable pointerEvents

### LINKED ISSUE #1160: IE11 double-clicking word result in click icons in toolbar (underline/bolded..)
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Using IE11 when double clicking a word, the icons in the toolbar are accidentally clicked.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://issues.liferay.com/browse/LPS-91194
It is hard to see in the AE Demo and noticeable in Liferay.
1. Use AE demo in IE11
2. Double click a word so the toolbar appears.

Result: A icon is clicked, in this case the font style is selected.

**What is the expected behavior?**
No icon in the toolbar should be clicked when double clicking a word.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
IE11, 2.0.0-beta.1

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://github.com/liferay/alloy-editor/issues/1160
https://issues.liferay.com/browse/LPS-91194

I included `pointerEvents: 'none'` to the style to prevent any unwanted button selections. Then applied a `transitionend` event listener. Only when the transition has completed will the pointerEvents be removed and allow the user to interact with the toolbar.
Let me know if there are any questions or comments about this.

Thank you.

### CODE REVIEW

**Comment by julien** [comment]
Just started reviewing :)

File: src/components/base/widget-position.js [hunk 1]
```diff
@@ -332,6 +333,14 @@ export default WrappedComponent =>
 					opacity: 1,
 				});
 			});
+
+			if(domElement.$){
```
Comment (wincent) [inline src/components/base/widget-position.js]: nit: space after the `if `

And also after the `=>` below.

You should probably run `npm run format`.

**Comment by julien** [comment]
@fortunatomaldonado I tested in IE11 and it seems to work fine, however take into account @wincent 's comment concerning formatting.
Thanks!

File: src/components/base/widget-position.js (hunk 1 above)
Comment (fortunatomaldonado) [reply src/components/base/widget-position.js]: Hello @wincent,

Thank you, I made the format changes. I was unable to run npm run format though.

**Comment by fortunatomaldonado** [comment]
Hello @julien,

Sounds good. I added the necessary format changes. Let me know if there is anything else I should do.
Thank you.

**Comment by julien** [comment]
Just started reviewing :)
